-- ============================================================
-- active_skills dataset
-- ============================================================

TRUNCATE TABLE active_skills RESTART IDENTITY CASCADE;

INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (1, 'Hydro Jet', 9, 30, 2, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (2, 'Power Shot', 8, NULL, 4, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (3, 'Aqua Gun', 9, 40, 4, 'Hurls a ball of water straight at an enemy.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (4, 'Bubble Blast', 9, 65, 13, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (5, 'Icicle Cutter', 7, 55, 10, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (6, 'Aqua Burst', 9, 100, 30, 'Creates a giant ball of water and hurls it at an enemy.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (7, 'Hydro Laser', 9, 150, 55, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (8, 'Geyser Gush', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (9, 'Spark Blast', 3, 30, 2, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (10, 'Shockwave', 3, 40, 4, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (11, 'Lightning Gale', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (12, 'Lock-on Laser', 3, 70, 15, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (13, 'Lightning Streak', 3, 75, 16, 'Generates a lightning bolt that moves forward in a line') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (14, 'Tri-Lightning', 3, 90, 22, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (15, 'Lightning Strike', 3, 120, 40, 'Acts as a lightning rod, calling down thunderbolts that electrocute the surrounding area.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (16, 'Lightning Bolt', 3, 150, 55, 'Charges electric energy before blasting enemies with a powerful shock.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (17, 'Railbolt', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (18, 'Electric Ball', 3, 50, 9, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (19, 'Power Bomb', 8, 70, 15, 'Charges a massive amount of energy before firing a large destructive ball.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (20, 'Stone Blast', 6, 55, 10, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (21, 'Sand Tornado', 6, 80, 18, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (22, 'Spinning Roundhouse', 6, 100, 21, 'Anubis''s exclusive skill.Anubis special skill. Performs a spin kick with its strong legs, cutting down enemies over a wide area.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (23, 'Forceful Charge', 6, 120, 28, 'Anubis''s exclusive skill.Pursues its foe with a high speed dash while releasing energy and unleashes a powerful punch.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (24, 'Ground Smash', 6, 140, 35, 'Anubis''s exclusive skill.Leaps high into the air before diving to the ground with a punch. The force of the impact deals damage over a wide area.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (25, 'Rock Lance', 6, 150, 55, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (26, 'Sand Twister', 6, 160, 60, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (27, 'Rocky Impact', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (28, 'Spirit Fire', 4, 45, 7, 'Shoots fireballs towards an enemy. The fireballs explode after a short distance, generating smaller fireballs that spread forward.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (29, 'Dragon Burst', 2, 55, 10, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (30, 'Flare Storm', 4, 80, 18, 'Generates two flaming tornadoes on either side before launching them at an enemy') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (31, 'Dragon Breath', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (32, 'Beam Comet', 2, 140, 50, 'Jetragon''s exclusive skill.Flies at enemies on illuminated wings while firing innumerable beams. The Beams explode on impact.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (33, 'Fire Ball', 4, 150, 55, 'The ball explodes over a wide area upon impact.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (34, 'Dragon Meteor', 2, 150, 55, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (35, 'Beam Slicer', 2, 130, 45, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (36, 'Meteorain', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (37, 'Star Mine', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (38, 'Bog Blast', 6, 40, 4, 'Hurls sticky mud at an enemy.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (39, 'Seed Machine Gun', 5, 50, 9, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (40, 'Grass Tornado', 5, 80, 18, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (41, 'Earth Impact', 6, 100, 30, 'Mammorest''s exclusive skill.Uses massive body to shake the earth, dealing damage over a wide area.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (42, 'Spine Vine', 5, 95, 25, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (43, 'Solar Blast', 5, 150, 55, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (44, 'Wind Burst', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (45, 'Air Cannon', 8, 25, 2, 'Quickly fires a burst of highly pressurized air.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (46, 'Cloud Tempest', 8, 90, 15, 'Fenglope''s exclusive skill.Charges forward while manipulating the atmosphere to create a pressurized wind tunnel around itself.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (47, 'Acid Rain', 9, 80, 18, 'Creates acidic clouds that pour down acid rain on enemies.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (48, 'Blizzard Spike', 7, 130, 45, 'Creates a giant lump of ice and hurls it at an enemy. It deals damage to those in the surrounding area upon impact.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (49, 'Pal Blast', 8, 150, 55, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (50, 'Holy Burst', 8, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (51, 'Dark Ball', 1, 40, 4, 'Unleashes a sphere of darkness that slowly tracks down the enemy.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (52, 'Shadow Burst', 1, 55, 10, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (53, 'Spirit Flame', 1, 75, 16, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (54, 'Nightmare Ball', 1, 100, 30, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (55, 'Dark Laser', 1, 150, 55, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (56, 'Dark Whisp', 1, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (57, 'Dragon Cannon', 2, 30, 2, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (58, 'Slither Slam', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (59, 'Plasma Funnel', 3, 65, 13, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (60, 'Wind Cutter', 5, 30, 2, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (61, 'Ice Missile', 7, 30, 3, 'Creates ice lances in the air that fly towards enemies') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (62, 'Iceberg', 7, 70, 15, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (63, 'Crystal Wing', 7, 110, 24, 'Frostallion''s exclusive skill.Dashes forward while creating frigid air around its wings, using them to slash enemies.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (64, 'Crystal Breath', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (65, 'Double Blizzard Spike', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (66, 'Absolute Frost', 7, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (67, 'Focus Shot', 5, 65, 9, 'Robinquill''s exclusive skill.Takes aim while drawing its bow before loosing a powerful shot at an enemy.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (68, 'Seed Mine', 5, 65, 13, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (69, 'Ignis Blast', 4, 30, 2, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (70, 'Flare Arrow', 4, 55, 10, 'Fires three flaming arrows in succession that home in on an enemy.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (71, 'Ignis Breath', 4, 70, 15, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (72, 'Botanical Smash', 5, 60, 8, 'Dinossom''s exclusive skill.Uses large tail to smash the ground in front of it, damaging enemies over a wide area.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (73, 'Implode', 8, 230, 55, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (74, 'Megaton Implode', 8, 500, 55, 'Tocotoco''s exclusive skill.Risks life to cause a massive explosion. Those who perish for their duty become glistening stars in the night sky.}}') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (75, 'Jumping Claw', 1, 55, 7, 'Loupmoon''s exclusive skill.Leaps forward and attacks twice with vicious claws imbued with dark energy.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (76, 'Phoenix Flare', 4, 135, 28, 'Faleris''s special skill.Covers its body in a tornado of flames before charging forward.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (77, 'Ignis Rage', 4, 120, 40, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (78, 'Raging Flame Wave', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (79, 'Gale Claw', 8, 60, 8, 'Galeclaw''s exclusive skill.Soars through the air with its talons outstretched forward.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (80, 'Shell Spin', 6, 65, 9, 'Digtoise''s exclusive skill.Moves while spinning its whole body at high speeds.Drills through enemies, dealing continuous damage.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (81, 'Stone Cannon', 6, 70, 15, 'Digs up a boulder and hurls it at an enemy') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (82, 'Poison Blast', 1, 30, 2, 'Hurls poison sludge at an enemy}}') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (83, 'Fluffy Tackle', 8, 40, 4, 'Melpaca''s exclusive skill.Charges forward while clad in an aura of sublime adorableness.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (84, 'Ignis Charge', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (85, 'Volcanic Burst', 4, 100, 45, 'Reptyro''s exclusive skill.Raises its front legs before slamming them onto the ground, causing volcanic eruptions under its enemies.It simultaneously bombards them with volcanic bombs from above.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (86, 'Spirit Dash', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (87, 'Muscle Slam', 8, 80, 12, 'Broncherry''s exclusive skill.Turns sideways before tackling enemies in front of it, sending them flying into the air.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (88, 'Poison Shower', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (89, 'Crushing Punch', 5, 85, 18, 'Mossanda''s exclusive skill.Winds up its fist before striking an enemy with a devastating punch.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (90, 'Bountiful Protection', 5, 0, 240, 'Lyleen`s exclusive skill.Restores health to all allies within range using the power of healing.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (91, 'Poison Fog', 1, 0, 30, 'Generates a fog of poison in front, causing the opponent to become poisoned.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (92, 'Chicken Rush', 8, 30, 1, 'Chikipi''s exclusive skill.Flies at enemies in its sights, attacking them with its sharp beak.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (93, 'Double Fang', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (94, 'Fierce Fang', 8, 45, 2, 'Direhowl''s special skill. Swiftly leaps at an enemy and bites into them.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (95, 'Reckless Charge', 8, 55, 2, 'Rushoar''s special skill.Takes aim at a foe and rushes at them with a made charge.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (96, 'Diamond Rain', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (97, 'Giga Horn', 6, 75, 11, 'Warsect''s exclusive skill.Skewers enemies with its four sturdy horns.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (98, 'Snow Bowling', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (99, 'Comet Strike', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (100, 'Blast Cannon', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (101, 'Hydra Charge', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (102, 'Azure Dracoflare', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (103, 'Celestial Vortex', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (104, 'Divine Disaster', 1, 160, 45, 'Shadowbeak''s exclusive skill.Charges forward while generating orbs of light that automatically capture enemies. The orbs automatically capture enemies, before releasing a barrage of lasers.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (105, 'Divine Disaster II', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (106, 'Bubble Rain', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (107, 'Creeping Bubbles', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (108, 'Aqua Blade', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (109, 'Tidal Charge', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (110, 'Maelstrom', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (111, 'Grand Breach', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (112, 'Aqua Tornado', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (113, 'Tornado Attack', 8, 65, 13, 'Nitewing''s exclusive skill. Generates a tornado before soaring towards its target.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (114, 'Fuddler Tunneler', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (115, 'Kingly Slam', 8, 100, 21, 'Kingpaca''s exclusive skill.Kingpaca exclusive skill. Leaps high into the air before smashing into an enemy with its massive body.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (116, 'Emperor Slide', 7, 70, 10, 'Penking''s exclusive skill.Lies on its belly while generating frozen air all around it before sliding at enemies at high speed.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (117, 'Firefist Breathstorm', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (118, 'Thunderstorm', 3, 160, 60, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (119, 'Phantom Peck', 1, 55, 7, 'Cawgnito''s exclusive skill.Teleports next to an enemy before attacking with its beak.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (120, 'Blazing Horn', 4, 50, 9, 'Arsox''s exclusive skill.Takes aim and rushes at an enemy with a mad dash.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (121, 'Double Fang (Fire)', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (122, 'Fierce Fang (Fire)', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (123, 'Daring Flames', 4, 75, 10, 'Kitsun''s exclusive skill.Charges forward with great speed while clad in intense blue flames.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (124, 'Double Fang (Electric)', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (125, 'Fierce Fang (Electric)', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (126, 'Beckon Lightning', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (127, 'Splash Tackle', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (128, 'Lightning Claw', 3, 90, 22, 'Grizzbolt''s exclusive skill.After leaping at an enemy and tearing at it twice with its electrically charged claws, it attacks the ground, sending an electric shock throughout the area.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (129, 'Heavy Thunder Tank', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (130, 'Lethal Laser', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (131, 'Antler Uppercut', 8, 50, 5, 'Eikthyrdeer''s exclusive skill.Charges at foes and uses antlers to launch them into the air.If using while riding, the direction of the charge can be controlled.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (132, 'Punch Flurry', 8, 40, 1, 'Cattiva''s special skill.Pursues enemies, repeatedly punching them with both its fists.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (133, 'Ground Pound', 8, 85, 14, 'Gorirat''s exclusive skill.Pounds the ground twice before leaping into the air and unleashing a powerful punch.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (134, 'Mystic Whirlwind', 2, 70, 10, 'Elphidran''s exclusive skill.Generates twin whirlwinds imbued with a mysterious power that pursues enemies.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (135, 'Spinning Staff', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (136, 'Rocket Slam', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (137, 'Brawn Impact', 4, 150, 38, 'Blazamut''s exclusive skill. Raises and inflates its arms, then slams them together, causing a massive explosion in the surrounding area.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (138, 'Cat Press', 8, 60, 9, 'Grintale''s exclusive skill.Grins menacingly before leaping into the air and smashing foes with its body.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (139, 'Sand Blast', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (140, 'Dark Charge', 1, 85, 14, 'Pyrin Noct''s exclusive skill.Charges forward while clad in a veil of dark flames.Flames continue to burn in its trajectory.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (141, 'Flame Breath', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (142, 'Blast Punch', 3, 85, 14, 'Mossanda Lux''s exclusive skill.Winds up its fist before pummeling an enemy with a flurry of electrically charged punches.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (143, 'Mud Horn', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (144, 'Freezing Charge', 7, 65, 9, 'Reindrix''s exclusive skill.Charges at an enemy with antlers adorned in ice.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (145, 'Hellfire Claw', 4, 70, 10, 'Incineram''s exclusive skill.Draws near enemies using its left claw to slash them into the air before cutting them down with its right claw.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (146, 'Nightmare Claw', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (147, 'Lightning Smash', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (148, 'Jumping Stinger', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (149, 'Magma Serpent', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (150, 'Kerauno', 3, 100, 30, 'Orserk''s exclusive skill.Summons a blade of lightning while leaping into the air before throwing it at an enemy.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (151, 'Polykeraunos', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (152, 'Spear Thrust', 8, 120, 40, 'Paladius''s exclusive skill.Clads itself in holy power before charging forward with its spear. The shield in its other hand protects from attacks during the charge.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (153, 'Radiant Barrage', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (154, 'Twin Spears', 1, 120, 40, 'Necromus''s exclusive skill.Clads its twin spears with vicious whirlwinds and charges forward, thrusting them one after the other.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (155, 'Apocalypse', 1, 110, 55, 'Generates several dark vortexes in the surrounding area.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (156, 'Tempest Blizzard', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (157, 'Iaigiri', 4, 65, 9, 'Bushi''s exclusive skill.After Holding the sword, he appears in front of the enemy in an instant and unleashes a Ultra-fast sword draw attack.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (158, 'Lightning Dive', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (159, 'Rush Beak', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (160, 'Leaping Roundhouse', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (161, 'Blizzard Claw', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (162, 'Volcanic Fang', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (163, 'Lawn Bowling', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (164, 'Dark Wing', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (165, 'Needle Spear', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (166, 'Bee Quiet', 5, 250, 55, 'Beegarde''s exclusive skill.Risks its life to cause a violent explosion, but receives the honor of falling in battle.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (167, 'Frozen Press', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (168, 'Frost Burst', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (169, 'Roly Poly', 8, 35, 1, 'Lamball''s special skill.Curls into a ball, rolling after any enemies in its way.Becomes dizzy and unable to move after the attack ends.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (170, 'Dark Cannon', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (171, 'Umbral Surge', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (172, 'Dark Arrow', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (173, 'Nightmare Ray', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (174, 'Flame Waltz', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (175, 'Nightmare Bloom', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (176, 'Circle Vine', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (177, 'Splash', 9, 90, 22, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (178, 'Curtain Splash', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (179, 'Earth Dash', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (180, 'Rockburst', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (181, 'Air Blade', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (182, 'Wholehearted Stance', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (183, 'Flame Wall', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (184, 'Flame Funnel', 4, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (185, 'Magna Crush', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (186, 'Evil Slash', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (187, 'Multicutter', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (188, 'Volcanic Rain', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (189, 'Seigetsu Blade', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (190, 'Moonlight Beam', 8, 170, 40, 'Selyne''s exclusive skill. Stores energy in the moon on its back, then fires a crescent-shaped beam forward.') ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (191, 'Seigetsu Flash', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (192, 'Ground Cutter', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (193, 'Unique_ScorpionMan_Uppercut', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (194, 'TriSpark', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (195, 'Thunder Rain', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (196, 'Rumble Combo', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (197, 'Icicle Line', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (198, 'Wind Edge', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (199, 'Phoenix Tide', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (200, 'Double Fang (Ground)', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (201, 'Fierce Fang (Ground)', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (202, 'Crash Dash', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (203, 'Frost Talon', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (204, 'Glacial Impact', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (205, 'Satellite Bit', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (206, 'Beam Slash', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (207, 'Astral Ray', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (208, 'Cosmic Meteor', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (209, 'Omega Laser', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (210, 'Double Fang (Dark)', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (211, 'Fierce Fang (Dark)', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (212, 'Icicle Bullet', 7, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (213, 'All Range Thunder', 3, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (214, 'Flash Charge', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (215, 'Bolt Blink', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (216, 'Webstrike Impact', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (217, 'Grudge Barrage', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (218, 'Soul Drain', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (219, 'Holy Nova', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (220, 'Charge Cannon', 2, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (221, 'Aegis Charge', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (222, 'Spectral Steed', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (223, 'Lethal Step', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (224, 'Snow Claw', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (225, 'Freeze Wall', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (226, 'Daring Shadowstorm', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (227, 'Thunder Tempest', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (228, 'Stone Claw', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (229, 'Thunder Spear', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (230, 'Dark Shot', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (231, 'Hydro Slicer', 9, 130, 45, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (232, 'Aqua Surge', 9, 160, 56, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (233, 'Unique_OctopursGirl_InkJet', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (234, 'Torrential Blast', 9, 110, 35, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (235, 'Thalassonic Laser', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (236, 'Hydro Spin', 9, 95, 15, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (237, 'Konoha Flip', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (238, 'Reflect Leaf', 5, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (239, 'Crosswind', 5, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (240, 'Chaotic Spray', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (241, 'Dash Kick', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (242, 'Thunderslide', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (243, 'Deep Breath', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (244, 'High Breach', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (245, 'Trigger Happy', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (246, 'Divine Wing', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (247, 'Sacred Rain', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (248, 'Purifying Light', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (249, 'Lotus Bloom', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (250, 'Black Quilled Ballet', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (251, 'Ice Gale Strike', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (252, 'Bull Rush', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (253, 'Raging Bull Rush', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (254, 'Snow Rush', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (255, 'Raging Snow Rush', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (256, 'Rapid Kick', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (257, 'Raid Cutter', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (258, 'Glacial Plunge', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (259, 'Double Fang (Ice)', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (260, 'Fierce Fang (Ice)', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (261, 'Frostcall', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (262, 'Magma Spit', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (263, 'Magma Laser', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (264, 'Ice Spit', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (265, 'Ice Laser', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (266, 'Mummy Rush', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (267, 'Silver Steed', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (268, 'Royal Step', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (269, 'Horn Burst', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (270, 'Ice Burst', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (271, 'Rocket Arm', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (272, 'Root Cannon', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (273, 'Dark Root', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (274, 'Somersault Scratch', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (275, 'Rolling Scratch', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (276, 'Thunder Uppercut', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (277, 'Holy Press', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (278, 'Sumo Stomp', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (279, 'Dark Nova', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (280, 'Flame Cutter', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (281, 'Shell Charge', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (282, 'Comet Barrage', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (283, 'Tail Slash', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (284, 'Blazing Beam', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (285, 'Flower Stomp', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (286, 'Trickster Show', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (287, 'Poison Scatter', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (288, 'Lantern Flame', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (289, 'Missile Burst', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (290, 'Giant Spore', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (291, 'Spore Burst', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (292, 'Poison Promenade', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (293, 'Toxic Dance', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO active_skills (id, name, element_id, power, cooldown_seconds, description) VALUES (294, 'Cube Press', NULL, NULL, NULL, NULL) ON CONFLICT (id) DO NOTHING;